### ISSUE TITLE
Use abide for calling convention information

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#11]
In the architecture-specific backends, we reason about which registers can be used for arguments and which are preserved by calling conventions.  We should use the abide library (https://github.com/GaloisInc/abide) for that instead of duplicating the information.  That would also tell us about stack layout.

Note that reasoning at the level of ABIs is not necessarily safe (unless we back that up with a separate analysis to prove that the function respects the ABI). This is a separate issue.

**Comment by danmatichuk** [comment]
Ideally a general solution for #19 would allow us to not rely on calling conventions at all.
