### ISSUE TITLE
Triage failures on challenge 3

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#130]
Inspecting the proof of challenge 3 shows a number of failures that don't have obvious explanations (and seem likely to be false positives). We should fix the easy ones and document complex cases. Note that they could relate to fixpoints (#82)

**Comment by danmatichuk** [comment]
This is the current state of Challenge 3 on the solver. At the moment we are able to run the verifier up to `init_bumper` where it times out as a result of failing to infer some constant propagation.

1. Context-insensitivity is preventing constant propagation from retaining concrete region from malloc’d pointer
    * Added additional context to nodes in the PairGraph which allow each function call site to be given a distinct domain
        * Configurable at the top-level -> can be made more fine-grained
    * This is a fairly heavy-handed solution, as it is not generally clear when it should be used.
    * **TODO: Proper solution involves computing more precise “frames” for function calls.**
        * i.e. if we know a function does not modify a value, then any constraints on it at each call site can be soundly propagated across the function call
        * smells like separation logic
2. Symbolic naturals are problematic for a number of reasons
    * Added some low-level functions for extracting/injecting symbolic integers from symbolic naturals while avoiding positivity checks
        * **TODO: Needs to be applied systematically -> pointer construction/deconstruction should use a unified interface**
        * Proper solution would remove SymNat from LLVMPointer type entirely.
3. Rewrites for value/constant propagation are not applying reliably
    * When a rewrite system is non-trivial, some rewrite orderings will resolve to a constant while others will not.
        * This should not be an issue for the solver, but the terms are difficult to interpret without inlining constants.
    * Challenge is currently blocked on a problem that I believe should be trivial after simplification -> need to apply rewrites to see where the hard part is
    * Solution: **TODO: When augmenting the rewriting environment, apply the incoming rewrites to the left-hand side of all existing rewrites.**
4. Determined that the value domain propagation was failing due to improper handling of PLT stubs
    * Problem: Stack frame was not being propagated correctly
    * Solution: Updated logic for stack frame stitching to add case for handling PLT.
        * No warning mechanism for loss of precision in the value domain.
        * Suggestion: **TODO: Better top-level debugging tools that allow us to track values as they propagate**
        1. Describe the need for special case in code for PLT. 
        2. Alternatively, reuse stubs from inline callee work (based on llvm mem model - Should 2 diff mem models be unified? Then we can use same overrides for inline callee and verifier work. Avoids 2 copies of stubs) 
5. Determined that undefined pointer operations are likely causing loss of precision 
    * Solution: Remove uninterpreted functions from memory model
    * Problem: Symbolic regions are still introduced from some undefined operations (depends on operation order, etc).
        * Solution: **TODO: Either explicitly assume the correctness of pointer operations *or* use the solver to intelligently construct pointer terms which avoid containing symbolic values**
