### ISSUE TITLE
Use hinted names in formulas and explanations

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#134]
We should use name hints (e..g, function names, parameter names, local variable names) to improve the display of diagnostics, formulas, and explanations.

* We can introduce function argument names by using them as the names of initial parameters passed in registers when building the initial symbolic states of functions (note: we can use the abide library to provide the mapping from argument positions to registers)
* We can introduce names of locals (or other stack variables) when printing memory references

Note that the traversal of memory terms might be verbose, but should not be particularly challenging. Introducing function argument names in the described way will work for register arguments, but does not work for arguments passed on the stack.

**Comment by thebendavis** [comment]
completed initial version
