### ISSUE TITLE
Fix Z3 and CVC4 support

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#167]
We have options to use Z3 and CVC4, but both of those solvers currently fail. It seems like we generate invalid SMT for Z3 (due to a struct scoping issue). I forget the failure mode for CVC4, but it also fails.

**Comment by robdockins** [comment]
FWIW, I've just run a quick experiment. The test suite is currently failing if we switch to CVC4 or Z3.  I can't tell for certain what the issues are, but my hypothesis is that it seems like they just take longer to solve problems, and this causes heuristics to fail and we get less precise results. It is also possible that genuine solver errors are getting masked by exception handling, but it seems like maybe those solvers are mostly working?

A few testing examples for the strongest post verifier also seem to be working as I expect with these solvers.

Tested with CVC4 1.8 and Z3 4.8.14
