### ISSUE TITLE
Maintain abstraction boundary of `MemCell.MemCellPred`

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#207]
The constructor for `MemCellPred` is exported for a few uses, but it should be hidden behind the module interface.

**Comment by travitch** [comment]
Thanks - I think that'll be a very good improvement

**Comment by danmatichuk** [comment]
Fixed in https://github.com/GaloisInc/pate/commit/137175ee39904c4d53898602b80471157ee7181f by introducing `What4.PredMap`
