### ISSUE TITLE
Clean up mostly unused 'EquivRelation'

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#213]
The type 'Pate.EquivRelation' is intended to abstract away the specific equivalence relation we might be trying to prove (i.e. possibly proving some relaxed congruence rather than exact equality). Currently this is only actually used for exact equality, and it's not clear in general how we might define or prove more complex relations.

For the moment we should just remove this type and assume that exact equality is the desired relation, until we have a clearer picture of how we might want to relax the verifier.

**Comment by lcasburn** [comment]
Blocking [#238](https://github.com/GaloisInc/pate/issues/238)
