### ISSUE TITLE
MVP for the strongest postcondition verifier

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/pate#214]
Tracking ticket for producing a minimum viable product version of the forward dataflow/strongest postcondition verifier. PR #203 is represents the very first step in this direction.

This ticket is for discussions regarding what represents an MVP for this feature and what tasks remain to get there.

**Comment by travitch** [comment]
The remaining issue is to establish a strongest postcondition verifier test suite

**Comment by travitch** [comment]
Depends on #279
