### ISSUE TITLE
Service reads from concrete memory concretely

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#223]
For reads from memory at concrete addresses that are known to be in read-only memory, we should service them concretely because it is safe to do so (as long as memory protection is not subverted).

We can plumb the macaw `Memory` into the memory statement handlers in the trace memory model. This structure has the necessary permissions information to determine what address ranges are safe to read from. We may want to index the memory to avoid having to re-do range calculations, but it might not be necessary.

**Comment by robdockins** [comment]
It seems like the right way to do this is to sink the Macaw `Memory` down into the `MemTraceImpl` and check for concrete reads from read-only memory inside `readMemState`. What do you think?

**Comment by travitch** [comment]
Yeah we can do that or possibly just capture it as an argument to `macawTraceExtensions` and pass it to `execMacawStmtExtension`

**Comment by robdockins** [comment]
I think the same `macawTraceExtensions` value was used by both binaries. We could do that, but I guess we'd have to split it into two separate extension values.

**Comment by travitch** [comment]
Oh, good point. Then `MemTraceImpl` would probably be best
