### ISSUE TITLE
Global regions are not handled very carefully, and may be unsafe

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#226]
In the original design, we assigned global memory region 2 and the stack region 1. We never actually used that global region, and instead use 0 as the global region. That isn't inherently problematic, but we need to think through how pointer and bitvector operations interact.  Some issues we've noticed so far:

- The (trace) memory model is currently extremely unsound and assigns region 0 to all values read from memory
- There is a value allocated as the global region (which is never used)
- The mapping of macaw pointers into the verifier formerly assigned them the region attached to the macaw pointer, which was incorrect (#225)

Arguably, maybe careful treatment is not important. If we see a read in the memory model from a pointer value that is concrete, its region only matters if we are carefully modeling dynamic memory allocation (or if it is stack based). Otherwise, we can just service it as if it was a global pointer.

**Comment by thebendavis** [comment]
completed
