### ISSUE TITLE
Add "unary" abstract domain information to the SP verifier

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/pate#270]
Right now, the only information tracked in the strongest-postcondition verifier is the "binary" relational information that indicates what values are (in)equivalent between the two binaries.  We also need to track more traditional "unary" domain information for each binary.  This will let us, e.g. track what memory region registers point into, and could also allow precision-increasing analyses (e.g., value-set) to be enabled.

**Comment by danmatichuk** [comment]
@travitch This feels a bit general for the July milestone. Should we move this to just the end of phase milestone and consider the #275 PR (for constant propagation) to be the goal?

**Comment by travitch** [comment]
Yes, I think the near-term goal is constant propagation (and we can add more if we need later)

**Comment by thebendavis** [comment]
completed
