### ISSUE TITLE
Add a VC at call sites for the TOC pointer on PPC64

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#28]
Right now, the heuristic for computing the pre-domain of functions assumes that the TOC pointer in r2 will be correct. We are not yet checking that callers of functions set this value correctly (but should eventually). Note that there are two possible VCs:
- At least check that the original and modified binary have the same value
- It could be desirable to check that the TOC value is actually *correct*

**Comment by danmatichuk** [comment]
Related to #270
