### ISSUE TITLE
Replace `rebindExpr` with `rebindWithFrame` to avoid `inNewFrameWithVars`

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#37]
Proof results (i.e. computed pre-domains in the form of state predicates) are abstracted over the initial state of the machine by representing that state as bound variables. These are rebound to the post-state of the preceding block slice when used as a post-domain target. Currently this rebinding is done using `rebindExpr`, which abuses the internal function definition mechanism of what4 to instantiate those bound variables. Expressions containing bound variables cannot directly be used in solver queries, however, unless they have been explicitly fixed via `What4.Protocol.Online.inNewFrameWithVars`, which adds additional complexity and will make it difficult to transition to offline solvers.

`SimState.rebindWithFrame` is a more general function that supports arbitrary sub-expression rewrites given a binding environment. Using this would allow the initial state to be instead represented as free variables (i.e. `What4.freshConstant`), which would allow us to avoid using `inNewFrameWithVars`. It would have the added benefit of not needing to carry around the evidence that the expressions used to bind the initial state were all necessarily bound variables.

**Comment by travitch** [comment]
I'd like to clarify my understanding on this one. Are you proposing a straight up replacement of all uses of `rebindExpr` with `rebindWithFrame`? Is the implication then that all variables in the resulting formula would be bound and that `inNewFrameWithVars` would simply no longer be necessary?

I'm partway through the transition to offline backends in #39 and I think this might be the last thing I need to do (aside from some very careful goal management).

**Comment by danmatichuk** [comment]
Yes, the intention would be to replace all insurances of `rebindExpr` with `rebindWithFrame` and correspondingly replace the variable binding environments with `AssumptionFrame`s. The effect would be the same, but we would just be doing the term replacement ourselves, rather than relying on any built-in variable binding functionality.
