### ISSUE TITLE
Generalize and stabilize control flow alignment

### ISSUE THREAD

**Issue by thebendavis** [GaloisInc/pate#388]
Complete control flow alignment needed to support Target7

**Comment by lcasburn** [comment]
- Scripts have been updated
 - Found test that had been marked as expected failure but it shouldn't have been. Fixed. 
 - Tests running locally but not yet working on CI

**Comment by danmatichuk** [comment]
Correction: found a test that is timing out locally. It is a bug that's causing the verifier to loop, I'm investigating it now.
