### ISSUE TITLE
binja: Check for missing sync in target7

### ISSUE THREAD

**Issue by thebendavis** [GaloisInc/pate#389]
Once #388 is complete, make sure we see the synchronization/merge points we expect in the Binary Ninja UI for target7

**Comment by jim-carciofini** [comment]
The graph for each function entry now flows to a return node, except for a few tail call nodes that flow to a "None" node that is a sink. Looking at hooking those up to the return node.

**Comment by jim-carciofini** [comment]
Ben commented in  Mattermost:
> great - thanks for the fix re: those None nodes! I'll let Dan chime in regarding whether there is more data available we want to wire in, but IMO tail calls as sinks in the PATE overview graph seems sufficient and lack of anything "beyond" it doesn't seem to negatively impact the operator's understanding of the GirdIDPS example at least

**Comment by thebendavis** [comment]
Closing - in an offline discussion we determined that with these recent fixes we are now satisfied with the rendering of tail calls.
