### ISSUE TITLE
binary ninja plugin: support dark themes

### ISSUE THREAD

**Issue by thebendavis** [GaloisInc/pate#401]
In our Binary Ninja plugin, we've been using colors that work best with the "Classic" theme. However, dark mode themes are the default and very popular - it'd be nice if our plugin also worked well in these environments.

Some things to check:

- [x] the trace diff views (in the equivalence condition windows and instruction tree windows) are hard to read in dark themes like "Ninja Edit"
- [x] use of colors for "equivalence condition here" block vs. "only in original" vs. "only in patched" blocks in the PATE overview graph. E.g. in some themes the pink/purple used on the patched blocks and the equiv condition block color look similar, can we make them more distinct?

**Comment by jim-carciofini** [comment]
I am working on tweaking the diff colors to match the binja theme. I need a binja C++ API exported to the Python API. Biinja developer on slack channel indicated it was a quick fix. Waiting....

**Comment by jim-carciofini** [comment]
@thebendavis I believe this is working now for all the Pate displays. I think the "Ninja Edit" theme looks the best. Can you review and comment or close?

**Comment by thebendavis** [comment]
@jim-carciofini looks great, thank you!

Closing as complete in 4f7ba8bba390c5d825153b6a3fcc08530cd683ee
