### ISSUE TITLE
Review updated target 7 script & create GUI replay 

### ISSUE THREAD

**Issue by lcasburn** [GaloisInc/pate#403]

**Comment by lcasburn** [comment]
depends #402

**Comment by jim-carciofini** [comment]
In progress, waiting for Dan to answer questions posed in Mattermost.

**Comment by jim-carciofini** [comment]
Done in https://gitlab-ext.galois.com/pate/pate-binja-demos/-/commit/5a98bebf3740a65138a37fc4faf7e8266350448a
