### ISSUE TITLE
Document path directives feature in user manual

### ISSUE THREAD

**Issue by lcasburn** [GaloisInc/pate#429]

**Comment by jim-carciofini** [comment]
I can provide GUI screen shots when I have things working. Do you want them here, or added to the doc in which case can I get a pointer to the doc.

**Comment by thebendavis** [comment]
> I can provide GUI screen shots when I have things working. Do you want them here, or added to the doc in which case can I get a pointer to the doc.

Thanks @jim-carciofini! The goal for this issue would be that we'd update the Binary Ninja plugin usage section of the User Manual https://github.com/GaloisInc/pate/blob/master/docs/user-manual/user-manual.pdf (source files in `docs/user-manual/`) to describe the path directive feature on the running packet example. If you'd like to take a swing at that then that would be wonderful, or if you'd just like to drop screenshots in the github issue thread here for discussion first/instead then that would also be great.

**Comment by jim-carciofini** [comment]
Screen shots attached. I am available to discuss final tweaks anytime tomorrow other than a meeting from 12:00-12:30 CST.
![01-Trace-Before-constraint](https://github.com/user-attachments/assets/14fa90fb-2129-49d7-8960-2a963aa867f4)
![02-Constraint-Dialog](https://github.com/user-attachments/assets/e61f6953-304e-4e70-8c72-a2082d8efb12)
![03-Constraint-Added](https://github.com/user-attachments/assets/8b719d5f-7856-49e0-8e93-fef440ed1401)
![04-Trace-After-Constraint](https://github.com/user-attachments/assets/d5d0465a-e408-4a9b-8024-4936136025b3)

**Comment by jim-carciofini** [comment]
Adding @danmatichuk
