### ISSUE TITLE
Classify errors as non-fatal/recoverable

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#78]
Currently most thrown errors are treated as catastrophic and cause verification to bail out entirely. Now that the proof is reified as data, we have an opportunity to localize errors to a branch of the proof tree, while preserving the rest of the proof structure.
Each error site should be classified as either being catastrophic (i.e. verification cannot sensibly continue), localized/recoverable (i.e. failure is problematic, but its scope may be limited to a branch of the proof), or heuristic (i.e. failure simply results to a default value).
The main outcome from this treatment will be more structured error output, but also it will cause the tool to still report something meaningful even if a bug prevents an entire binary from being verified.

**Comment by travitch** [comment]
This is better now, but still could use some additional work.
