### ISSUE TITLE
Allow manually-defined frames for functions

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#88]
For function calls that are dynamically-linked, or otherwise not interesting for the purposes of verifying a patch, we need the ability to axiomatize their frames in order to reasonably bound their effects. For example, we need to be able to declare that `printf` has no observable effects on memory and only reads from some constrained domain.

**Comment by travitch** [comment]
This is partially handled as of #102. That PR added a mechanism for providing customized summaries of missing functions. It currently assumes ABI compliance, but is flexible enough to support more precise per-target summaries.
