### ISSUE TITLE
Finalize and merge 'dm/challenge3-wip' branch

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#92]
This branch adds a number of fixes for making it possible to run the equivalence check on the main binary for challenge 3.  Specifically it adds:

* simple caching for previously proven triples to avoid redundant proofs
* simple error handling: all errors for any proof excursion are caught and propagate backwards an exact equivalence pre-domain

**Comment by travitch** [comment]
Merged as of ee1da96de1e0ba9453e43a175d5ba257eb8cb3ac
