### ISSUE TITLE
Slices overlap

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#99]
Many of our slices overlap. I don't think this is a huge problem, but it can be confusing for users browsing the proof. It also might imply substantial duplicated work. We should investigate why some slices are huge and overlapping.

**Comment by danmatichuk** [comment]
Was this addressed when Rob made some changes to the code that tries to find the blocks related to a particular entry point?

**Comment by travitch** [comment]
I think this was a problem particular to the weakest precondition solver, and is probably obsolete as we move away from that. I don't think it was fixed by rob's changes, but we can mark it obsolete anyway.
